name: Update NCAA Stats

on:
  schedule:
    - cron: "0 0 * * *"   # every day at midnight UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create credentials.json
        run: echo "${{ secrets.GSHEETS_KEY }}" > credentials.json

      - name: Run scraper
        run: python scraper.py
